// <auto-generated />
namespace SistemaGestionCliente.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreandoMigracionConTablaProvincia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreandoMigracionConTablaProvincia));
        
        string IMigrationMetadata.Id
        {
            get { return "201711122359322_CreandoMigracionConTablaProvincia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
